# 02 · Voir les tables SQL et les features

Ce notebook montre, **pour un client précis**, les lignes brutes de chaque table d'historique
puis le **résumé** (les features) que calcule la requête SQL correspondante.

👉 Changez `CLIENT` dans la cellule suivante pour explorer un autre client.

In [1]:
import duckdb
import pandas as pd

from credit_risk_scoring.config import DUCKDB_PATH
from credit_risk_scoring.features import SQL_DIR, read_sql

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 200)

con = duckdb.connect(str(DUCKDB_PATH), read_only=True)

def sql(query):
    """Exécute une requête SQL et affiche le résultat sous forme de tableau."""
    return con.execute(query).df()

CLIENT = 185175   # identifiant SK_ID_CURR du client à explorer

## 0. Les tables disponibles

`SHOW TABLES` liste les tables de la base DuckDB. Vous pouvez écrire **n'importe quelle requête SQL** dans `sql("...")`.

In [2]:
sql("SHOW TABLES")

                    name
0       POS_CASH_balance
1       application_test
2      application_train
3                 bureau
4         bureau_balance
5    credit_card_balance
6  installments_payments
7   previous_application

In [3]:
# Colonnes et types d'une table
sql("DESCRIBE installments_payments")

              column_name column_type null   key default extra
0              SK_ID_PREV      BIGINT  YES  None    None  None
1              SK_ID_CURR      BIGINT  YES  None    None  None
2  NUM_INSTALMENT_VERSION      DOUBLE  YES  None    None  None
3   NUM_INSTALMENT_NUMBER      BIGINT  YES  None    None  None
4         DAYS_INSTALMENT      DOUBLE  YES  None    None  None
5      DAYS_ENTRY_PAYMENT      DOUBLE  YES  None    None  None
6          AMT_INSTALMENT      DOUBLE  YES  None    None  None
7             AMT_PAYMENT      DOUBLE  YES  None    None  None

## 1. La demande de crédit du client

In [4]:
sql(f"""
    SELECT SK_ID_CURR, TARGET, DAYS_BIRTH, DAYS_EMPLOYED, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY
    FROM application_train
    WHERE SK_ID_CURR = {CLIENT}
""")

   SK_ID_CURR  TARGET  DAYS_BIRTH  DAYS_EMPLOYED  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY
0      185175       0      -23196         365243           50400.0    454500.0      20151.0

Après nettoyage par `01_application.sql` (ratios ajoutés, anomalie corrigée, genre retiré) :

In [5]:
sql(f"""
    SELECT SK_ID_CURR, AGE_YEARS, DAYS_EMPLOYED, DAYS_EMPLOYED_ANOM,
           CREDIT_INCOME_RATIO, ANNUITY_INCOME_RATIO, CREDIT_TERM, CREDIT_GOODS_RATIO
    FROM ({read_sql('01_application.sql')})
    WHERE SK_ID_CURR = {CLIENT}
""")

   SK_ID_CURR  AGE_YEARS  DAYS_EMPLOYED  DAYS_EMPLOYED_ANOM  CREDIT_INCOME_RATIO  ANNUITY_INCOME_RATIO  CREDIT_TERM  CREDIT_GOODS_RATIO
0      185175  63.507187           <NA>                   1             9.017857              0.399821     0.044337                 1.0

## 2. Remboursements passés (`installments_payments`)

**Avant** : une ligne par paiement. `DAYS_INSTALMENT` = date prévue, `DAYS_ENTRY_PAYMENT` = date du paiement
(en jours avant la demande). Si `DAYS_ENTRY_PAYMENT` > `DAYS_INSTALMENT`, le paiement est en retard.

In [6]:
sql(f"""
    SELECT SK_ID_PREV, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT,
           DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT AS jours_de_retard,
           AMT_INSTALMENT, AMT_PAYMENT
    FROM installments_payments
    WHERE SK_ID_CURR = {CLIENT}
    ORDER BY SK_ID_PREV, NUM_INSTALMENT_NUMBER
""")

    SK_ID_PREV  NUM_INSTALMENT_NUMBER  DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  jours_de_retard  AMT_INSTALMENT  AMT_PAYMENT
0      1751523                      1          -1959.0             -1974.0            -15.0       10308.825    10308.825
1      1751523                      2          -1929.0             -1942.0            -13.0       10308.825    10308.825
2      1751523                      3          -1899.0             -1911.0            -12.0       10308.825    10308.825
3      1751523                      4          -1869.0             -1886.0            -17.0       10308.825    10308.825
4      1751523                      5          -1839.0             -1802.0             37.0       10308.825      735.300
5      1751523                      5          -1839.0             -1851.0            -12.0       10308.825     9573.525
6      1751523                      6          -1809.0             -1802.0              7.0       10308.825    10308.825
7      1751523                      7          -1779.0             -1802.0            -23.0       10308.825       70.875
8      1751523                      7          -1779.0             -1764.0             15.0       10308.825    10237.950
9      1751523                      8          -1749.0             -1764.0            -15.0       10308.105      112.050
10     1751523                      8          -1749.0             -1746.0              3.0       10308.105    10196.055
11     1889778                      1           -237.0              -230.0              7.0        4732.245     4732.245
12     1889778                      2           -230.0              -230.0              0.0           1.755        1.755
13     1889778                      3           -227.0              -227.0              0.0       90000.000    90000.000
14     1889778                      4           -207.0              -226.0            -19.0        2211.570       89.010
15     1889778                      4           -207.0              -211.0             -4.0        2211.570     2122.560
16     1889778                      5           -211.0              -211.0              0.0         127.440      127.440
17     1889778                      6           -203.0              -203.0              0.0        2250.000     2250.000
18     1889778                      7           -176.0              -178.0             -2.0        5755.365     5755.365
19     1889778                      8           -178.0              -178.0              0.0          94.635       94.635
20     1889778                      9           -145.0              -145.0              0.0        5644.080     5644.080
21     1889778                     10           -145.0              -145.0              0.0         205.920      205.920
22     1889778                     11           -115.0              -115.0              0.0        5525.910     5525.910
23     1889778                     12           -115.0              -115.0              0.0         324.090      324.090
24     1889778                     13            -84.0               -85.0             -1.0        5408.550     5408.550
25     1889778                     14            -85.0               -85.0              0.0        1341.450     1341.450
26     1889778                     15            -54.0               -65.0            -11.0        5237.235     5237.235
27     1889778                     16            -65.0               -65.0              0.0        1512.765     1512.765
28     1889778                     17            -23.0               -24.0             -1.0        5063.175     5063.175
29     1889778                     18            -24.0               -24.0              0.0        1686.825     1686.825
30     2490891                      1           -313.0              -314.0             -1.0       21747.825   697500.000
31     2490891                      1           -313.0              -314.0             -1.0      675752.175   697500.000
32     2490891                      2           -283.0              -290.0             -7.0        2989.350     2989.350
33     2490891                      3           -253.0              -261.0             -8.0        2989.350     2989.350
34     2490891                      4           -223.0              -245.0            -22.0      107520.255   107520.255

**Après** `04_installments.sql` : une seule ligne qui résume tout cet historique.

In [7]:
sql(f"SELECT * FROM ({read_sql('04_installments.sql')}) WHERE SK_ID_CURR = {CLIENT}")

   SK_ID_CURR  INST_N_INSTALMENTS  INST_LATE_RATIO  INST_LATE_30_RATIO  INST_MEAN_DAYS_LATE  INST_MAX_DAYS_LATE  INST_UNDERPAID_RATIO  INST_TOTAL_UNPAID  INST_LATE_RATIO_LAST_YEAR
0      185175                  31          0.16129            0.032258             2.225806                37.0                   0.0                0.0                   0.043478

## 3. Crédits dans d'autres organismes (`bureau`)

In [8]:
sql(f"""
    SELECT SK_ID_BUREAU, CREDIT_ACTIVE, CREDIT_TYPE, DAYS_CREDIT, AMT_CREDIT_SUM, AMT_CREDIT_SUM_DEBT,
           AMT_CREDIT_SUM_OVERDUE
    FROM bureau
    WHERE SK_ID_CURR = {CLIENT}
""")

   SK_ID_BUREAU CREDIT_ACTIVE      CREDIT_TYPE  DAYS_CREDIT  AMT_CREDIT_SUM  AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_OVERDUE
0       6023988        Closed  Consumer credit        -1193        360000.0                  0.0                     0.0
1       6023989        Closed  Consumer credit        -1491        387000.0                  0.0                     0.0
2       6023990        Active  Consumer credit         -238        126000.0              98770.5                     0.0

Historique mensuel de ces crédits (`bureau_balance`) : nombre de mois par statut
(`0` = à jour, `1` à `5` = retard croissant, `C` = clôturé, `X` = inconnu).

In [9]:
sql(f"""
    SELECT bb.SK_ID_BUREAU, bb.STATUS, COUNT(*) AS nb_mois
    FROM bureau_balance bb
    JOIN bureau b USING (SK_ID_BUREAU)
    WHERE b.SK_ID_CURR = {CLIENT}
    GROUP BY ALL
    ORDER BY 1, 2
""")

   SK_ID_BUREAU STATUS  nb_mois
0       6023988      0       10
1       6023988      X        1
2       6023989      0       10
3       6023989      X        1
4       6023990      0        8

In [10]:
sql(f"SELECT * FROM ({read_sql('02_bureau.sql')}) WHERE SK_ID_CURR = {CLIENT}")

,SK_ID_CURR,BUREAU_N_CREDITS,BUREAU_N_ACTIVE,BUREAU_ACTIVE_RATIO,BUREAU_N_BAD_DEBT,BUREAU_CREDIT_CARD_RATIO,BUREAU_TOTAL_CREDIT,BUREAU_TOTAL_DEBT,BUREAU_DEBT_CREDIT_RATIO,BUREAU_TOTAL_OVERDUE,BUREAU_MAX_DAYS_OVERDUE,BUREAU_MAX_AMT_OVERDUE,BUREAU_N_PROLONGATIONS,BUREAU_OLDEST_CREDIT_DAYS,BUREAU_LAST_CREDIT_DAYS,BUREAU_LATE_MONTHS_RATIO,BUREAU_WORST_STATUS
0,185175,3,1,0.333333,0,0.0,873000.0,98770.5,0.113139,0.0,0,NaN,0.0,-1491,-238,0.0,0

## 4. Demandes précédentes chez Home Credit (`previous_application`)

In [11]:
sql(f"""
    SELECT SK_ID_PREV, NAME_CONTRACT_TYPE, NAME_CONTRACT_STATUS, AMT_APPLICATION, AMT_CREDIT,
           CNT_PAYMENT, DAYS_DECISION
    FROM previous_application
    WHERE SK_ID_CURR = {CLIENT}
    ORDER BY DAYS_DECISION
""")

   SK_ID_PREV NAME_CONTRACT_TYPE NAME_CONTRACT_STATUS  AMT_APPLICATION  AMT_CREDIT  CNT_PAYMENT  DAYS_DECISION
0     1751523     Consumer loans             Approved          70821.0     62064.0          8.0          -1999
1     2490891         Cash loans             Approved         675000.0    790830.0         60.0           -343
2     1889778    Revolving loans             Approved         135000.0    135000.0          0.0           -343
3     2381667         Cash loans              Refused         900000.0    900000.0         36.0            -26

In [12]:
sql(f"SELECT * FROM ({read_sql('03_previous_application.sql')}) WHERE SK_ID_CURR = {CLIENT}")

,SK_ID_CURR,PREV_N_APPLICATIONS,PREV_APPROVED_RATIO,PREV_REFUSED_RATIO,PREV_CANCELED_RATIO,PREV_CREDIT_APPLICATION_RATIO,PREV_MEAN_CREDIT,PREV_MEAN_N_PAYMENTS,PREV_LAST_DECISION_DAYS,PREV_LAST_REFUSAL_DAYS
0,185175,4,0.75,0.25,0.0,1.011988,471973.5,26.0,-26,-26

## 5. Cartes de crédit (`credit_card_balance`)

Une ligne par mois. Utilisation du plafond = `AMT_BALANCE / AMT_CREDIT_LIMIT_ACTUAL`.

In [13]:
sql(f"""
    SELECT SK_ID_PREV, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL,
           ROUND(AMT_BALANCE / NULLIF(AMT_CREDIT_LIMIT_ACTUAL, 0), 2) AS utilisation,
           AMT_DRAWINGS_ATM_CURRENT, SK_DPD
    FROM credit_card_balance
    WHERE SK_ID_CURR = {CLIENT}
    ORDER BY MONTHS_BALANCE DESC
    LIMIT 12
""")

    SK_ID_PREV  MONTHS_BALANCE  AMT_BALANCE  AMT_CREDIT_LIMIT_ACTUAL  utilisation  AMT_DRAWINGS_ATM_CURRENT  SK_DPD
0      1889778              -1   102627.900                   247500         0.41                       0.0       0
1      1889778              -2    99384.795                   247500         0.40                       0.0       0
2      1889778              -3   109542.780                   247500         0.44                       0.0       0
3      1889778              -4   112008.780                   225000         0.50                       0.0       0
4      1889778              -5   114310.125                   225000         0.51                       0.0       0
5      1889778              -6   116640.495                   225000         0.52                       0.0       0
6      1889778              -7   115233.165                   135000         0.85                  112500.0       0
7      1889778              -8    95824.620                   135000         0.71                   90000.0       0
8      1889778              -9        0.000                   135000         0.00                       NaN       0
9      1889778             -10        0.000                   135000         0.00                       NaN       0
10     1889778             -11        0.000                   135000         0.00                       NaN       0

In [14]:
sql(f"SELECT * FROM ({read_sql('05_credit_card.sql')}) WHERE SK_ID_CURR = {CLIENT}")

   SK_ID_CURR  CC_N_CARDS  CC_MEAN_UTILIZATION  CC_MAX_UTILIZATION  CC_MEAN_ATM_DRAWINGS  CC_LATE_MONTHS_RATIO  CC_MAX_DPD
0      185175           1             0.395133            0.853579               25312.5                   0.0           0

## 6. Crédits à la consommation (`POS_CASH_balance`)

In [15]:
sql(f"""
    SELECT SK_ID_PREV, MONTHS_BALANCE, CNT_INSTALMENT, CNT_INSTALMENT_FUTURE, NAME_CONTRACT_STATUS, SK_DPD
    FROM POS_CASH_balance
    WHERE SK_ID_CURR = {CLIENT}
    ORDER BY SK_ID_PREV, MONTHS_BALANCE DESC
    LIMIT 12
""")

    SK_ID_PREV  MONTHS_BALANCE  CNT_INSTALMENT  CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD
0      1751523             -57             8.0                    0.0            Completed       0
1      1751523             -58             8.0                    1.0               Active       0
2      1751523             -59             8.0                    2.0               Active       0
3      1751523             -60             8.0                    3.0               Active      16
4      1751523             -61             8.0                    4.0               Active       0
5      1751523             -62             8.0                    5.0               Active       0
6      1751523             -63             8.0                    6.0               Active       0
7      1751523             -64             8.0                    7.0               Active       0
8      1751523             -65             8.0                    8.0               Active       0
9      2490891              -7             4.0                    0.0            Completed       0
10     2490891              -8            60.0                   57.0               Active       0
11     2490891              -9            60.0                   58.0               Active       0

In [16]:
sql(f"SELECT * FROM ({read_sql('06_pos_cash.sql')}) WHERE SK_ID_CURR = {CLIENT}")

   SK_ID_CURR  POS_N_LOANS  POS_LATE_MONTHS_RATIO  POS_MAX_DPD  POS_REMAINING_RATIO
0      185175            2               0.071429           16                  0.0

## 7. Le résultat final : la ligne du client dans `features.parquet`

Toutes les features réunies sur **une seule ligne** : c'est ce que le modèle verra.

In [17]:
pd.set_option("display.max_rows", 200)   # afficher les 172 lignes
features = pd.read_parquet("../data/processed/features.parquet")
features.loc[features["SK_ID_CURR"] == CLIENT].T.rename(columns=lambda _: "valeur")

                                          valeur
SK_ID_CURR                                185175
TARGET                                         0
NAME_CONTRACT_TYPE                    Cash loans
FLAG_OWN_CAR                                   Y
FLAG_OWN_REALTY                                N
CNT_CHILDREN                                   0
AMT_INCOME_TOTAL                         50400.0
AMT_CREDIT                              454500.0
AMT_ANNUITY                              20151.0
AMT_GOODS_PRICE                         454500.0
NAME_TYPE_SUITE                           Family
NAME_INCOME_TYPE                       Pensioner
NAME_EDUCATION_TYPE             Higher education
NAME_FAMILY_STATUS                       Married
NAME_HOUSING_TYPE              House / apartment
REGION_POPULATION_RELATIVE              0.035792
DAYS_BIRTH                                -23196
DAYS_REGISTRATION                        -8666.0
DAYS_ID_PUBLISH                            -5172
OWN_CAR_AGE                                  8.0
FLAG_MOBIL                                     1
FLAG_EMP_PHONE                                 0
FLAG_WORK_PHONE                                0
FLAG_CONT_MOBILE                               1
FLAG_PHONE                                     1
FLAG_EMAIL                                     0
OCCUPATION_TYPE                              NaN
CNT_FAM_MEMBERS                              2.0
REGION_RATING_CLIENT                           2
REGION_RATING_CLIENT_W_CITY                    2
WEEKDAY_APPR_PROCESS_START              THURSDAY
HOUR_APPR_PROCESS_START                       14
REG_REGION_NOT_LIVE_REGION                     0
REG_REGION_NOT_WORK_REGION                     0
LIVE_REGION_NOT_WORK_REGION                    0
REG_CITY_NOT_LIVE_CITY                         0
REG_CITY_NOT_WORK_CITY                         0
LIVE_CITY_NOT_WORK_CITY                        0
ORGANIZATION_TYPE                            XNA
EXT_SOURCE_1                            0.784226
EXT_SOURCE_2                            0.641098
EXT_SOURCE_3                            0.627991
APARTMENTS_AVG                               NaN
BASEMENTAREA_AVG                             NaN
YEARS_BEGINEXPLUATATION_AVG                  NaN
YEARS_BUILD_AVG                              NaN
COMMONAREA_AVG                               NaN
ELEVATORS_AVG                                NaN
ENTRANCES_AVG                                NaN
FLOORSMAX_AVG                                NaN
FLOORSMIN_AVG                                NaN
LANDAREA_AVG                                 NaN
LIVINGAPARTMENTS_AVG                         NaN
LIVINGAREA_AVG                               NaN
NONLIVINGAPARTMENTS_AVG                      NaN
NONLIVINGAREA_AVG                            NaN
APARTMENTS_MODE                              NaN
BASEMENTAREA_MODE                            NaN
YEARS_BEGINEXPLUATATION_MODE                 NaN
YEARS_BUILD_MODE                             NaN
COMMONAREA_MODE                              NaN
ELEVATORS_MODE                               NaN
ENTRANCES_MODE                               NaN
FLOORSMAX_MODE                               NaN
FLOORSMIN_MODE                               NaN
LANDAREA_MODE                                NaN
LIVINGAPARTMENTS_MODE                        NaN
LIVINGAREA_MODE                              NaN
NONLIVINGAPARTMENTS_MODE                     NaN
NONLIVINGAREA_MODE                           NaN
APARTMENTS_MEDI                              NaN
BASEMENTAREA_MEDI                            NaN
YEARS_BEGINEXPLUATATION_MEDI                 NaN
YEARS_BUILD_MEDI                             NaN
COMMONAREA_MEDI                              NaN
ELEVATORS_MEDI                               NaN
ENTRANCES_MEDI                               NaN
FLOORSMAX_MEDI                               NaN
FLOORSMIN_MEDI                               NaN
LANDAREA_MEDI                                NaN
LIVINGAPARTMENTS_MEDI                        NaN
LIVINGAREA_MEDI                              NaN
NONLIVINGAPARTMENTS_MEDI                     NaN
NONLIVINGAREA_MEDI                           NaN
FONDKAPREMONT_MODE                           NaN
HOUSETYPE_MODE                               NaN
TOTALAREA_MODE                               NaN
WALLSMATERIAL_MODE                           NaN
EMERGENCYSTATE_MODE                         <NA>
OBS_30_CNT_SOCIAL_CIRCLE                     0.0
DEF_30_CNT_SOCIAL_CIRCLE                     0.0
OBS_60_CNT_SOCIAL_CIRCLE                     0.0
DEF_60_CNT_SOCIAL_CIRCLE                     0.0
DAYS_LAST_PHONE_CHANGE                   -1999.0
FLAG_DOCUMENT_2                                0
FLAG_DOCUMENT_3                                1
FLAG_DOCUMENT_4                                0
FLAG_DOCUMENT_5                                0
FLAG_DOCUMENT_6                                0
FLAG_DOCUMENT_7                                0
FLAG_DOCUMENT_8                                0
FLAG_DOCUMENT_9                                0
FLAG_DOCUMENT_10                               0
FLAG_DOCUMENT_11                               0
FLAG_DOCUMENT_12                               0
FLAG_DOCUMENT_13                               0
FLAG_DOCUMENT_14                               0
FLAG_DOCUMENT_15                               0
FLAG_DOCUMENT_16                               0
FLAG_DOCUMENT_17                               0
FLAG_DOCUMENT_18                               0
FLAG_DOCUMENT_19                               0
FLAG_DOCUMENT_20                               0
FLAG_DOCUMENT_21                               0
AMT_REQ_CREDIT_BUREAU_HOUR                   0.0
AMT_REQ_CREDIT_BUREAU_DAY                    0.0
AMT_REQ_CREDIT_BUREAU_WEEK                   0.0
AMT_REQ_CREDIT_BUREAU_MON                    0.0
AMT_REQ_CREDIT_BUREAU_QRT                    0.0
AMT_REQ_CREDIT_BUREAU_YEAR                   2.0
DAYS_EMPLOYED                               <NA>
DAYS_EMPLOYED_ANOM                             1
AGE_YEARS                              63.507187
CREDIT_INCOME_RATIO                     9.017857
ANNUITY_INCOME_RATIO                    0.399821
CREDIT_TERM                             0.044337
CREDIT_GOODS_RATIO                           1.0
INCOME_PER_PERSON                        25200.0
EMPLOYED_AGE_RATIO                    -15.745948
BUREAU_N_CREDITS                               3
BUREAU_N_ACTIVE                                1
BUREAU_ACTIVE_RATIO                     0.333333
BUREAU_N_BAD_DEBT                              0
BUREAU_CREDIT_CARD_RATIO                     0.0
BUREAU_TOTAL_CREDIT                     873000.0
BUREAU_TOTAL_DEBT                        98770.5
BUREAU_DEBT_CREDIT_RATIO                0.113139
BUREAU_TOTAL_OVERDUE                         0.0
BUREAU_MAX_DAYS_OVERDUE                        0
BUREAU_MAX_AMT_OVERDUE                       NaN
BUREAU_N_PROLONGATIONS                       0.0
BUREAU_OLDEST_CREDIT_DAYS                  -1491
BUREAU_LAST_CREDIT_DAYS                     -238
BUREAU_LATE_MONTHS_RATIO                     0.0
BUREAU_WORST_STATUS                            0
PREV_N_APPLICATIONS                            4
PREV_APPROVED_RATIO                         0.75
PREV_REFUSED_RATIO                          0.25
PREV_CANCELED_RATIO                          0.0
PREV_CREDIT_APPLICATION_RATIO           1.011988
PREV_MEAN_CREDIT                        471973.5
PREV_MEAN_N_PAYMENTS                        26.0
PREV_LAST_DECISION_DAYS                      -26
PREV_LAST_REFUSAL_DAYS                       -26
INST_N_INSTALMENTS                            31
INST_LATE_RATIO                          0.16129
INST_LATE_30_RATIO                      0.032258
INST_MEAN_DAYS_LATE                     2.225806
INST_MAX_DAYS_LATE                          37.0
INST_UNDERPAID_RATIO                         0.0
INST_TOTAL_UNPAID                            0.0
INST_LATE_RATIO_LAST_YEAR               0.043478
CC_N_CARDS                                     1
CC_MEAN_UTILIZATION                     0.395133
CC_MAX_UTILIZATION                      0.853579
CC_MEAN_ATM_DRAWINGS                     25312.5
CC_LATE_MONTHS_RATIO                         0.0
CC_MAX_DPD                                     0
POS_N_LOANS                                    2
POS_LATE_MONTHS_RATIO                   0.071429
POS_MAX_DPD                                   16
POS_REMAINING_RATIO                          0.0

## 8. À vous de jouer

Quelques requêtes pour vous entraîner :

1. Combien de clients ont au moins un crédit en `Bad debt` dans `bureau` ?
2. Quel est le taux de défaut (`TARGET`) des clients qui ont déjà été refusés au moins une fois ?
3. Quels sont les 5 clients avec le plus d'échéances payées en retard ?

In [18]:
# Exemple pour la question 2
sql("""
    SELECT
        (p.SK_ID_CURR IS NOT NULL) AS deja_refuse,
        COUNT(*) AS nb_clients,
        ROUND(AVG(a.TARGET) * 100, 2) AS taux_defaut_pct
    FROM application_train a
    LEFT JOIN (SELECT DISTINCT SK_ID_CURR FROM previous_application
               WHERE NAME_CONTRACT_STATUS = 'Refused') p USING (SK_ID_CURR)
    GROUP BY 1
""")

   deja_refuse  nb_clients  taux_defaut_pct
0        False      207217             6.98
1         True      100294            10.32